[package]
name = "what-stack"
version = "0.1.0"
edition = "2024"
autobenches = false
authors = ["Ehsan Khan"]
description = "Universal Rust library for detecting project roots and technology stacks"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ehsan18t/what-stack"
documentation = "https://docs.rs/what-stack"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
missing_docs = "deny"
let_underscore_drop = "deny"
non_ascii_idents = "deny"

[lints.rustdoc]
bare_urls = "deny"
broken_intra_doc_links = "deny"



[target.'cfg(unix)'.dependencies]
libc = "0.2.186"


[dev-dependencies]
tempfile = "3.27.0"
gungraun = "0.18.2"


[profile.bench]
debug = true

[[bench]]
name = "benchmarks"
harness = false
test = false


[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
