[advisories]
unmaintained = "workspace"
ignore = []

[licenses]
confidence-threshold = 0.93
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Unicode-3.0",
  "Zlib",
]

[[licenses.clarify]]
name = "unicode-ident"
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [{ path = "LICENSE-UNICODE", hash = 0x3fb01745 }]

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
skip = []
deny = [
  { crate = "openssl", use-instead = "rustls" },
  { crate = "openssl-sys", use-instead = "rustls" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
